name: iOS CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Build IPA with Fastlane
        run: |
          cd ios
          bundle install
          bundle exec fastlane gym --scheme MyApp --export_method ad-hoc

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/build/MyApp.ipa

