export enum NotificationType {
    REQUEST_TRIP = 'REQUEST_TRIP',
    RESPONSE_TRIP = 'RESPONSE_TRIP',
    REQUEST_TRACKING = 'REQUEST_TRACKING',
    RESPONSE_TRACKING = 'RESPONSE_TRACKING',
    STOP_TRACKING = 'STOP_TRACKING'
}
